# config.yml
project:
  type: node
  config:
    buildScript: build
    startScript: start
    devScript: dev

provider:
  type: aws
  config: {}

environment: dev

steps:
  - lint
  - build
  - deploy

env:
  REDIS_URL: ${REDIS_URL}
  DATABASE_URL: ${DATABASE_URL}
  NODE_ENV: "production"
