project:
  type: node
  config:
    buildScript: build
    startScript: start
    appName: test

provider:
  type: aws
  config:
    dev:
      host: ${EC2_HOST}
      user: ${EC2_USER}
      keyPath: ${EC2_KEY}
      appPath: /home/ubuntu/USDT-Track

environment: dev

steps: 
  - build
  - deploy

env:
  DATABASE_URL: ${DATABASE_URL}
  REDIS_URL: ${REDIS_URL}
  NODE_ENV: ${NODE_ENV} 
